pub use self::component::Component;
pub use self::component::IsComponent;
pub use self::ecs_context::EcsContext;
pub use self::ecs_event::EcsEventType;
pub use self::ecs_event::IsEcsEvent;
pub use self::ecs_manager::EcsManager;
pub use self::ecs_event_context::EcsEventContext;
pub use self::entity_manager::EntityManager;
pub use self::entity::Entity;
pub use self::system::System;
pub use self::system_manager::SystemManager;
pub use self::system_manager::EventHandlers;

mod component;
pub mod components;
mod ecs_context;
mod ecs_event_context;
mod ecs_event;
mod ecs_manager;
mod entity_manager;
mod entity;
mod system;
pub mod events;
pub mod systems;
mod system_manager;
pub mod util;